#:kivy 1.9.0

<Card>:
	padding: 10
	height: 150
	size_hint: (None, None)
	orientation: 'vertical'

	canvas.before:
		Color:
			rgba: (1, 1, 1, 0.1)
		Rectangle:
			pos: self.pos
			size: self.size

<ScrollScreen>:
	view: view

	BoxLayout:
		orientation: 'vertical'

		BoxLayout:
			size: (64, 64)
			size_hint: (1, None)

			Button:
				text: "Some static button"
				color: (1, 0, 0, 1)
				background_color: (.3, .3, .3, 1)

		ScrollView:
			id: view
